# Generated by Django 3.1.3 on 2020-12-03 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(max_length=64)),
                ('designation', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=127)),
                ('main_indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter.indication')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_switchable', models.BooleanField(default=True)),
                ('indications', models.ManyToManyField(to='meter.Indication')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter.devicetype')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Включен'), (2, 'Выключен'), (3, 'Неизвестно')], default=3)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('mqtt_id', models.CharField(max_length=255)),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter.devicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter.device')),
                ('indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter.indication')),
            ],
        ),
    ]
