# Generated by Django 3.1.3 on 2020-12-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0004_auto_20201207_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicegroup',
            name='devices',
            field=models.ManyToManyField(blank=True, to='meter.Device'),
        ),
    ]
