# Generated by Django 3.1.3 on 2020-12-07 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0005_auto_20201207_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meter.devicemodel'),
        ),
    ]
